version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "embedded-hal"
      versions: ["^0.2"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
